### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by mynameisfiber** [mschuerig/docker-subsonic#5]
Could there be a method so that I can enforce HTTPS on subsonic?

**Comment by mschuerig** [comment]
Not that I know of. I recommend putting subsonic behind a proxy that handles this.

**Comment by mynameisfiber** [comment]
In that case it may be easiest more easily expose some of subsonic's configuration.  Particularly the `SUBSONIC_CONTEXT_PATH` configuration variable

**Comment by mschuerig** [comment]
Send a pull request and I'll look into it (next year).
